// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        AircncHomeList: typeof import('./pages/Home/AircncHomeList.vue')['default']
        AircncHomeTabs: typeof import('./pages/Home/AircncHomeTabs.vue')['default']
        AircncPagination: typeof import('./components/Pagination/AircncPagination.vue')['default']
        AircncRoomDetails: typeof import('./pages/RoomDetails/AircncRoomDetails.vue')['default']
        AircncRoomDetailsDropdown: typeof import('./pages/RoomDetails/AircncRoomDetailsDropdown.vue')['default']
        AircncRoomDetailsSharePopup: typeof import('./pages/RoomDetails/AircncRoomDetailsSharePopup.vue')['default']
        Auth: typeof import('./pages/Auth/index.vue')['default']
        ElButton: typeof import('element-plus/lib')['ElButton']
        ElCol: typeof import('element-plus/lib')['ElCol']
        ElConfigProvider: typeof import('element-plus/lib')['ElConfigProvider']
        ElContainer: typeof import('element-plus/lib')['ElContainer']
        ElForm: typeof import('element-plus/lib')['ElForm']
        ElFormItem: typeof import('element-plus/lib')['ElFormItem']
        ElHeader: typeof import('element-plus/lib')['ElHeader']
        ElIcon: typeof import('element-plus/lib')['ElIcon']
        ElImage: typeof import('element-plus/lib')['ElImage']
        ElInput: typeof import('element-plus/lib')['ElInput']
        ElMain: typeof import('element-plus/lib')['ElMain']
        ElMenu: typeof import('element-plus/lib')['ElMenu']
        ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
        ElPagination: typeof import('element-plus/lib')['ElPagination']
        ElPopover: typeof import('element-plus/lib')['ElPopover']
        ElRow: typeof import('element-plus/lib')['ElRow']
        ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
        ElTabPane: typeof import('element-plus/lib')['ElTabPane']
        ElTabs: typeof import('element-plus/lib')['ElTabs']
        Footer: typeof import('./components/layout/Footer/index.vue')['default']
        Header: typeof import('./components/layout/Header/index.vue')['default']
        Home: typeof import('./pages/Home/index.vue')['default']
        IEpPicture: typeof import('~icons/ep/picture')['default']
        MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
        NotFound: typeof import('./pages/NotFound/index.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
